<?php

return [
    'name' => 'Kailash Machine Tools',
    'legal_name' => 'Kailash Machine Tools',
    'alternate_names' => [
        'Shree Ganesh Pharmatech',
        'Ganesh Machine Tools',
        'Kailash Pharmatech',
    ],
    'tagline' => 'Speeding Up Your Production, Scaling Up Your Success.',
    'subtitle' => 'Advance Technology Pharmaceuticals & Packaging Line Machinery Manufacturer',
    'founded' => 1989,
    'proprietor' => 'Hitesh Mevada',
    'founder' => 'Late Shri Chandubhai Mevada',
    'phone' => '+91 98255 78818',
    'phone_alt' => '+91 98250 18210',
    'whatsapp' => '919825578818',
    'email' => 'info@pharmaceuticalsmachines.com',
    'email_alt' => 'shreeganeshpharmatech@gmail.com',
    'email_new' => 'kailashmachinetools@gmail.com',
    'website' => 'www.pharmaceuticalsmachines.com',
    'address' => [
        'street' => '4, Devashray Arcade & Industrial Estate',
        'locality' => 'S.P Ring Road, Vinjol Circle, Hathijan Circle, Vatva',
        'city' => 'Ahmedabad',
        'region' => 'Gujarat',
        'postal_code' => '382445',
        'country' => 'IN',
        'country_name' => 'India',
        'lat' => 22.9470,
        'lng' => 72.6261,
    ],
    'hours' => [
        'Mon-Sat' => '10:00 - 19:00',
        'Sun' => 'Closed',
    ],
    'socials' => [
        'linkedin' => null,
        'youtube' => null,
        'facebook' => null,
        'instagram' => null,
    ],
    'stats' => [
        'years' => 37,
        'machines_delivered' => '2,500+',
        'countries' => '15+',
        'clients' => '450+',
    ],
];
